### ISSUE TITLE
pyinstaller 打包exe时有问题

### ISSUE THREAD

**Issue by kingkasuo** [smallevilbeast/pyxcgui#2]
主要发生在ntchat和xcgui同时引入时，打包就卡住在
16231 INFO: Looking for dynamic libraries

![Screenshot_3](https://user-images.githubusercontent.com/792288/193238576-56c67cc5-2f8f-4343-8d97-b31d5a0d050b.png)

单纯的ntchat 或者 xcgui程序，用pyinstaller打包exe是正常的，我想这里应该是打包时ntchat和xcgui有冲突？

**Comment by smallevilbeast** [comment]
应该是pybind11库的bug 暂时可以修改下pyinstaller代码让打包通过

在Lib\site-packages\PyInstaller\building\build_main.py 中的687行加上
collected_packages.reverse()
